name: gear_up
description: "Gear Up Automotive Ecosystem"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management (إدارة الحالة)
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^7.6.4

  # Networking (الاتصال بالنت والذكاء الاصطناعي)
  dio: ^5.3.3
  google_generative_ai: ^0.2.0

  # Database (قواعد البيانات)
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.5.4

  # UI (التصميم)
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
  percent_indicator: ^4.2.3

  # Utilities (أدوات مساعدة)
  intl: ^0.20.2
  uuid: ^4.2.1
  image_picker: ^1.0.4
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/